/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_dac.h"
#include "fsl_rtc.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Alias for DAC0 peripheral */
#define DAC_1_PERIPHERAL DAC0
/* Definition of peripheral ID */
#define RTC_1_PERIPHERAL RTC
/* RTC_1 interrupt vector ID (number). */
#define RTC_1_SECONDS_IRQN RTC_Seconds_IRQn
/* RTC_1 interrupt handler identifier. */
#define RTC_1_SECONDS_IRQHANDLER RTC_Seconds_IRQHandler

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const dac_config_t DAC_1_config;
/* RTC configuration */
extern const rtc_config_t RTC_1_config;
/* Date and time structure */
extern rtc_datetime_t RTC_1_dateTimeStruct;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
