/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_clock.h"
#include "fsl_ftm.h"
#include "fsl_tpm.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Definition of peripheral ID */
#define FTM3_PERIPHERAL FTM3
/* Definition of the clock source frequency */
#define FTM3_CLOCK_SOURCE CLOCK_GetFreq(kCLOCK_BusClk)
/* Definition of the clock source frequency */
#define FTM3_TIMER_MODULO_VALUE (((FTM3_CLOCK_SOURCE/ (1U << (FTM3_PERIPHERAL->SC & FTM_SC_PS_MASK))) / 10000) - 1)
/* Definition of FTM3 channel/pair number 5 on Edge-aligned PWM */
#define FTM3_CHANNEL5_CHANNEL kFTM_Chnl_5
/* Definition of FTM3 channel/pair number 1 on Edge-aligned PWM */
#define FTM3_CHANNEL1_CHANNEL kFTM_Chnl_1
/* Definition of peripheral ID */
#define TPM2_PERIPHERAL TPM2
/* Definition of the clock source frequency */
#define TPM2_CLOCK_SOURCE 48000000UL
/* TPM2 interrupt vector ID (number). */
#define TPM2_IRQN TPM1_IRQn
/* TPM2 interrupt handler identifier. */
#define TPM2_IRQHANDLER 
/* Definition of TPM2 channel/pair number 1 on Edge-aligned PWM */
#define TPM2_CHANNEL1_CHANNEL kTPM_Chnl_1

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const ftm_config_t FTM3_config;
extern const tpm_config_t TPM2_config;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
